version: '3'

services:

    python:
        build:
            dockerfile: ./dockerfile
        depends_on:
            - "db"

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
