version: '3'

services:
    python:
        build:
            dockerfile: ./Dockerfile
        working_dir: /app
        command: python3 -m flask --app app/app.py run --host=0.0.0.0 --debug
        
        depends_on:
            - postgres
        volumes: 
            - ./source:/app
        env_file:
            - .env  
        ports:
            - ${APP_PORT}:5000
        networks: 
            - python-network
            - postgres-network
    
    cron:
        build:
            context: .
            dockerfile: ./docker/cron/Dockerfile
        depends_on:
            - postgres
        volumes: 
            - ./source:/app
        env_file:
            - .env
        networks:
            - cron-network
            - postgres-network

    postgres:
        image: postgres:alpine
        volumes:
            - postgres-volume:/var/lib/posgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        networks:
            - postgres-network
volumes:
    postgres-volume:
        driver: local

networks:
    python-network:
        driver: bridge
    cron-network:
        driver: bridge
    postgres-network:
        driver: bridge