version: '3'

services:
    python:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - "8000:8000"
        networks:
            - gerdisc_default

networks:
    gerdisc_default:
        external: true
