version: '3'

services:
    python:
        build:
            dockerfile: ./Dockerfile
            args:
                YEAR: ${YEAR}
                FILE: ${FILE}
        depends_on:
            - "db"
        env_file:
            - .env
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432     
        command: 
            psql -U postgres && 
            CREATE DATABASE infosProducao
