version: '3'

services:
    python:
        build:
            dockerfile: ./Dockerfile
        depends_on:
            - "postgres"
        env_file:
            - .env  
        ports:
            - 5000:5000
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pondoc
        ports:
            - 5434:5432
volumes:
  postgres:
    driver: local