version: '3'

services:
    python:
        build:
            dockerfile: ./Dockerfile
            args:
                YEAR: ${YEAR}
                FILE: ${FILE}
        depends_on:
            - "postgres"
        env_file:
            - .env  
    postgres:
        image: postgres:alpine
        volumes:
            - postgres:/var/lib/posgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pondoc
        ports:
            - 5432:5432
volumes:
  postgres:
    driver: local