version: '3'

services:

    python:
        build:
            dockerfile: ./Dockerfile
        depends_on:
            - "db"
        env_file:
            - .env
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
