version: '3'

services:
    python:
        build:
            dockerfile: ./Dockerfile
        depends_on:
            - "postgres"
        volumes: 
            - $PWD/out:$PWD/out
        env_file:
            - .env  
        ports:
            - 5000:5000
    postgres:
        image: postgres:alpine
        volumes:
            - postgres:/var/lib/posgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pondoc
        ports:
            - 5432:5432
volumes:
  postgres:
    driver: local